/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mborodin_javacourse_Main */

#ifndef _Included_com_mborodin_javacourse_Main
#define _Included_com_mborodin_javacourse_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mborodin_javacourse_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mborodin_javacourse_Main_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
