spring.application.name=lecture8-backend

#Properties to connect to SQLite
spring.datasource.url=jdbc:sqlite:db_lecture8
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
#SQLite doesn't need password but most DBs require it, so here is example how to set it.
#spring.datasource.username=postgres_user
#spring.datasource.password=postgres_password

spring.jpa.hibernate.ddl-auto=create
