#Properties for connection to SQLite
spring.datasource.url=jdbc:sqlite:db_cats
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create

#Properties for the program
app.max-cat-number=5

#Properties for the logs
logging.level.org.springframework.web=debug
logging.file.name=application.log